spring:
  application:
    name: api
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/coupon_example # basic
    username: root
    password: 1234 # 1234
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create #create
    show-sql: true
  redis:
    host: localhost
    port: 6379